[package]
name = "async-sse"
version = "5.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/http-rs/async-sse"
documentation = "https://docs.rs/async-sse"
description = "Async Server Sent Event parser and encoder"
readme = "README.md"
edition = "2018"
keywords = ["async", "server-sent-events", "sse", "client", "server"]
categories = []
authors = [
    "Renée Kooi <renee@kooi.me>",
    "Yoshua Wuyts <yoshuawuyts@gmail.com>",
]

[features]

[dependencies]
futures-lite = "2.5.0"
http-types = { version = "3.0.0", default-features = false }
log = "0.4.8"
memchr = "2.3.3"
pin-project-lite = "0.2.7"
async-channel = "1.1.1"

[dev-dependencies]
femme = "2.0.0"
async-std = { version = "1.6.0", features = ["attributes", "unstable"] }

[patch.crates-io]
http-types = { git = "https://github.com/tomgroenwoldt/http-types.git", branch = "bump-futures-lite" }
